FROM node:20-alpine
WORKDIR /app

# Frontend dependencies  
COPY package*.json ./
RUN npm ci

# Server dependencies
COPY server/package*.json ./server/
WORKDIR /app/server
RUN rm -rf node_modules && npm ci
WORKDIR /app

# Copy source code
COPY server ./server

EXPOSE 3003
CMD ["node", "server/multiplayer-service.js"]